version: '3.8'

services:
    rdbms:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: "1234"
            POSTGRES_USER: "ethereum"
            POSTGRES_DB: "cryptocurrency"
        volumes:
            - ./volumes/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"